# Generated by Django 5.2 on 2025-06-24 12:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeEmpacado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('responsable', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('libras_tradicional', models.PositiveIntegerField(default=0)),
                ('medias_tradicional', models.PositiveIntegerField(default=0)),
                ('cuartos_tradicional', models.PositiveIntegerField(default=0)),
                ('libras_premium', models.PositiveIntegerField(default=0)),
                ('medias_premium', models.PositiveIntegerField(default=0)),
                ('cuartos_premium', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CafeMolido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('responsable', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cantidad_baches', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CafeTostado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('responsable', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cantidad_baches', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CafeTrillado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('responsable', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(choices=[('KG', 'Kilogramos'), ('LB', 'Libras')], default='KG', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
