# Generated by Django 5.2 on 2025-04-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
