# Generated by Django 5.1.2 on 2025-04-22 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField()),
                ('cantidad', models.FloatField()),
                ('precio', models.IntegerField()),
                ('datos_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafe', to='proveedores.proveedor')),
            ],
        ),
    ]
