# Generated by Django 5.2 on 2025-06-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='unidad_medida',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('libra', 'Libra'), ('media_libra', 'Media Libra'), ('cuarto_libra', 'Cuarto de Libra'), ('kilo', 'Kilogramo')], default='unidad', max_length=20),
        ),
    ]
